// SHARED BY ACTIONS AND REDUCERS
module.exports = {
  SAMPLE_SET: 'SAMPLE_SET',

  USER_SET: 'USER_SET',
  XP_ADD: 'XP_ADD',
  XP_SUBTRACT: 'XP_SUBTRACT',
  SET_USER_XP: 'SET_USER_XP',
  XP_CLEAR: 'XP_CLEAR',
  USER_XP_ADD: 'USER_XP_ADD',
  USER_XP_SUBTRACT: 'USER_XP_SUBTRACT',
  GET_TOP_USERS_PROCESS: 'GET_TOP_USERS_PROCESS',
  SET_LOADED_USER: 'SET_LOADED_USER',
  CHECK_LEVEL: 'CHECK_LEVEL',

  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',

  SOCKET_MESSAGE: 'SOCKET_MESSAGE',
  SOCKET_ADD_ONLINE: 'SOCKET_ADD_ONLINE',
  SOCKET_DISCONNECT: 'SOCKET_DISCONNECT',

  SELECT_IMAGE_WARNING: 'SELECT_IMAGE_WARNING',
  SET_PICTURE: 'SET_PICTURE',
  SEND_PICTURE_SUCCESS: 'SEND_PICTURE_SUCCESS',
  SEND_PICTURE_FAIL: 'SEND_PICTURE_FAIL',
  SEND_PICTURE_REQUEST: 'SEND_PICTURE_REQUEST',

  GET_PICTURES: 'GET_PICTURES',
  GET_PICTURES_SUCCESS: 'GET_PICTURES_SUCCESS',
  GET_PICTURES_FAIL: 'GET_PICTURES_FAIL',
  GET_PICTURES_REQUEST: 'GET_PICTURES_REQUEST',

  SET_PHOTOS: 'SET_PHOTOS',
  SET_CONFIGS: 'SET_CONFIGS',
  GET_PHOTO_SIZE: 'GET_PHOTO_SIZE',
  SET_CURRENT_PHOTO: 'SET_CURRENT_PHOTO',
  SET_PHOTO_INDEX: 'SET_PHOTO_INDEX',

  SHOW_NEXT: 'SHOW_NEXT',

  GET_STATS_REQUEST: 'GET_STATS_REQUEST',
  GET_STATS_SUCCESS: 'GET_STATS_SUCCESS',
  GET_STATS_FAILURE: 'GET_STATS_FAILURE',
};
