// SHARED BY ACTIONS AND REDUCERS
module.exports = {
  SAMPLE_SET: 'SAMPLE_SET',

  USER_SET: 'USER_SET',
  XP_ADD: 'XP_ADD',
  XP_SUBTRACT: 'XP_SUBTRACT',
  SET_USER_XP: 'SET_USER_XP',

  SET_PICTURE: 'SET_PICTURE',
  SEND_PICTURE_SUCCESS: 'SEND_PICTURE_SUCCESS',
  SEND_PICTURE_FAIL: 'SEND_PICTURE_FAIL',
  SEND_PICTURE_REQUEST: 'SEND_PICTURE_REQUEST',

  GET_PICTURES: 'GET_PICTURES',
  GET_PICTURES_SUCCESS: 'GET_PICTURES_SUCCESS',
  GET_PICTURES_FAIL: 'GET_PICTURES_FAIL',
  GET_PICTURES_REQUEST: 'GET_PICTURES_REQUEST',
};
