const JAWBONE_BASE_API_URL = 'https://jawbone.com';
const JAWBONE_BASE_API_URL_TOKEN = 'https://jawbone.com';
const JAWBONE_AUTH_PATH = '/auth/oauth2/auth';
const JAWBONE_TOKEN_PATH = '/auth/oauth2/token';
const JAWBONE_DEFAULT_SCOPE = [ 'basic_read' ];

module.exports = {
  JAWBONE_BASE_API_URL: JAWBONE_BASE_API_URL,
  JAWBONE_AUTH_PATH: JAWBONE_AUTH_PATH,
  JAWBONE_TOKEN_PATH: JAWBONE_TOKEN_PATH,
  JAWBONE_DEFAULT_SCOPE: JAWBONE_DEFAULT_SCOPE,
  JAWBONE_BASE_API_URL_TOKEN: JAWBONE_BASE_API_URL_TOKEN
};
